### ISSUE TITLE
my_MaxPool2d,my_AvgPool2d

### ISSUE THREAD

**Issue by chenhaocs** [dongliangchang/Top-Down-Spatial-Attention-Loss#1]
Hi, thanks for your sharing. Could you share the definition of my_MaxPool2d,my_AvgPool2d

**Comment by chenhaocs** [comment]
> Hi, thanks for your sharing. Could you share the definition of my_MaxPool2d,my_AvgPool2d

I find it in the repo: PRIS-CV/Mutual-Channel-Loss, is it ?

**Comment by dongliangchang** [comment]
I have uploaded the related code.

**Comment by dongliangchang** [comment]
> 
> 
> > Hi, thanks for your sharing. Could you share the definition of my_MaxPool2d,my_AvgPool2d
> 
> I find it in the repo: PRIS-CV/Mutual-Channel-Loss, is it ?

YES.

**Comment by chenhaocs** [comment]
> I have uploaded the related code.

Thank you.
